name: 'actionoidcclient'
description: 'To test if the action toolkit package can be called from it'
author: 'Your name or organization here'
outputs:
  id_token:
    description: 'Returns ID token'

runs:
  using: 'node12'
  main: 'index.js'
